# Generated by Django 5.1 on 2024-09-14 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("betting", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bet",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="betslip",
            name="bets",
            field=models.ManyToManyField(to="betting.bet"),
        ),
        migrations.AddField(
            model_name="betslip",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bet_slips",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bets",
                to="betting.match",
            ),
        ),
        migrations.AddField(
            model_name="odds",
            name="match",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="odds",
                to="betting.match",
            ),
        ),
        migrations.AddField(
            model_name="bet",
            name="odds",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="betting.odds"
            ),
        ),
    ]
