# Generated by Django 5.1 on 2024-09-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team_a_image",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
        migrations.AddField(
            model_name="match",
            name="team_b_image",
            field=models.ImageField(blank=True, null=True, upload_to="team_images/"),
        ),
    ]
